### ISSUE TITLE
Social interractions: accounts

### ISSUE THREAD

**Issue by Godley** [WearableProject/Wearable-WebApp#1]
- consider what account format to use. It would be nice to integrate it with whatever schools use, but if there is no one unified "thing" every school will use then we should have our own account system.
- if creating our own, the backend part of this should entail having an online server holding a DB of usernames. Not sure if we should be storing anything else, possibly
  - name
  - likes
  - dislikes
    Anything more than that could pose issues with it being children's data, so I would avoid things like school or age.

**Comment by CatLamin** [comment]
There would likely be a teacher with minimal tech understanding in charge of inputting user data - if possible, set up an admin page for easy account management (possible to upload a simple CSV of names/surnames and usernames/passwords if already created elsewhere, otherwise randomly generate. It wouldn't be necessary for bands to communicate outside of an organisation at this stage if that helps.

Some schools may be possible to set up accoutns through active directory?!

Codecademy/Duolingo allows users to create their own accounts, but then link to a teacher who can monitor/reset passwords. Codecademy has quite an interesting teacher interface tbh!

**Comment by CatLamin** [comment]
Also, in an ideal world, the teacher interface would allow them to view the children's code so that they have some assessment evidence

**Comment by Godley** [comment]
Codecademy is a good shout. I've just nudged them to ask if their accounts could be integrated. We'd still need to store our own data somewhere but where I can avoid creating brand new accounts I think it's best to do that.
CSV/teacher admin page would deffo be doable - do you think we should integrate that into the app, or have a separate website? Each user could be given an admin rank if they're the teacher and then be able to view certain features the students can't. On the other hand tho it might be simpler to just have a separate place for admin

**Comment by CatLamin** [comment]
There are still a lot of primary schools not using Codecademy _yet_ but integration could still be valuable. I wonder how easy Codecademy are going to make my end of year rollover _sigh_
